// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIRV2WMxpU5VwGBIIYHXMqPh1yWVNIegY',
    appId: '1:787628066985:web:be5db978ef05d0006201b8',
    messagingSenderId: '787628066985',
    projectId: 'quizit-f33d2',
    authDomain: 'quizit-f33d2.firebaseapp.com',
    storageBucket: 'quizit-f33d2.appspot.com',
    measurementId: 'G-YHS4HQQXKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBggnflx7yx7R4mE7PdM9PutCz25noWvFc',
    appId: '1:787628066985:android:09f05c97e4bbd60d6201b8',
    messagingSenderId: '787628066985',
    projectId: 'quizit-f33d2',
    storageBucket: 'quizit-f33d2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyYmzyHlGaeHLu7HCJjS20A7JNofryZdQ',
    appId: '1:787628066985:ios:86c5dfc1a13bfc8c6201b8',
    messagingSenderId: '787628066985',
    projectId: 'quizit-f33d2',
    storageBucket: 'quizit-f33d2.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyYmzyHlGaeHLu7HCJjS20A7JNofryZdQ',
    appId: '1:787628066985:ios:86c5dfc1a13bfc8c6201b8',
    messagingSenderId: '787628066985',
    projectId: 'quizit-f33d2',
    storageBucket: 'quizit-f33d2.appspot.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIRV2WMxpU5VwGBIIYHXMqPh1yWVNIegY',
    appId: '1:787628066985:web:878899407106784d6201b8',
    messagingSenderId: '787628066985',
    projectId: 'quizit-f33d2',
    authDomain: 'quizit-f33d2.firebaseapp.com',
    storageBucket: 'quizit-f33d2.appspot.com',
    measurementId: 'G-R9FCT47GP0',
  );

}